#db:
#  image: postgres:latest
#  environment:
#    POSTGRES_USER: test_ddr
#    POSTGRES_PASSWORD:
#  env_file: dev.env

web:
  stdin_open: true
  tty: true
  build: .
  volumes:
    - .:/usr/src/app
#  links:
#    - db:db
  environment:
    - PYTHONUNBUFFERED=1
    - ENV=DEV
    - POSTGRES_HOST=db
    - POSTGRES_USER=test_ddr
  env_file: dev.env
  ports:
    - 8000:8000
  command: python manage.py runserver 0.0.0.0:8000
