# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 03:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('canonoff', models.BooleanField()),
                ('canmonitor', models.BooleanField()),
                ('adjustable', models.BooleanField()),
                ('app_type', models.IntegerField()),
                ('status', models.IntegerField()),
                ('control_panel', models.TextField(null=True)),
                ('room_id', models.IntegerField()),
                ('scm_id', models.IntegerField()),
                ('pos_x', models.IntegerField()),
                ('pos_y', models.IntegerField()),
                ('icon', models.TextField(null=True)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.TextField()),
                ('app_id', models.IntegerField()),
                ('created_date', models.DateTimeField()),
                ('volt', models.FloatField(null=True)),
                ('current', models.FloatField(null=True)),
                ('PF', models.FloatField(null=True)),
                ('kWh', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('houseID', models.IntegerField(primary_key=True, serialize=False)),
                ('total_electric_consumption', models.FloatField()),
                ('total_renewable_energy', models.FloatField()),
                ('abnormal_event', models.TextField()),
                ('electricity_rate', models.FloatField()),
                ('dsm_service', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InverterLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(unique=True)),
                ('Grid', models.FloatField()),
                ('Load', models.FloatField()),
                ('Inverter', models.FloatField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
            ],
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField()),
                ('conditions', models.TextField()),
                ('action', models.TextField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
            ],
        ),
        migrations.CreateModel(
            name='UserPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('Type', models.IntegerField()),
                ('sub_type', models.IntegerField()),
                ('me', models.BooleanField()),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household')),
            ],
        ),
        migrations.AddField(
            model_name='appliancelog',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household'),
        ),
        migrations.AddField(
            model_name='appliance',
            name='household',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Household'),
        ),
    ]
