# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 04:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20161208_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='houseID',
            new_name='id',
        ),
    ]
