# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20161208_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='name',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
