# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 04:18
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_household_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appliance',
            name='adjustable',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='canmonitor',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='canonoff',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='control_panel',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='pos_x',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='pos_y',
        ),
        migrations.RemoveField(
            model_name='appliance',
            name='scm_id',
        ),
        migrations.AddField(
            model_name='household',
            name='appliances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
