# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20161208_0418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='total_electric_consumption',
        ),
        migrations.RemoveField(
            model_name='household',
            name='total_renewable_energy',
        ),
        migrations.AddField(
            model_name='household',
            name='last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='mode',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='household',
            name='usage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=0),
            preserve_default=False,
        ),
    ]
