# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 20:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='appliances',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AlterField(
            model_name='household',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='household',
            name='mode',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='household',
            name='package',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='household',
            name='usage',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
