# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 22:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20161208_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='last_update',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
