# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20161209_0535'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('mode', models.TextField(default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='household',
            options={'ordering': ('id',)},
        ),
        migrations.RenameField(
            model_name='household',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
