# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-09 02:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_household_dr_enabled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='dr_enabled',
            new_name='dr_allowed',
        ),
    ]
