# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 16:57
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20161209_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='rules',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
