# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-01-23 13:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_household_appliances_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='household',
            name='event_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
